phabricator:
    build: docker/images/phabricator
    volumes: ['./docker/conf/fpm.conf:/usr/local/etc/php-fpm.conf', './:/var/platform', './docker/conf/php.ini:/usr/local/etc/php/conf.d/local.ini']
    links: [mariadb]
    environment:
      PLATFORM_DOCKER: commerce2x
      PHP_IDE_CONFIG: serverName=commerce2x.platform
      PHABRICATOR_MYSQL_PASS: root,
      PHABRICATOR_MYSQL_USER: root
      PHABRICATOR_MYSQL_HOST: mariadb
      PHABRICATOR_URI: http://phabricator.platform
mariadb:
    command: 'mysqld --user=root --verbose'
    image: mariadb
    ports: ['3306']
    volumes: ['./docker/data:/var/lib/mysql', './docker/conf/mysql.cnf:/etc/mysql/my.cnf']
    environment: { MYSQL_DATABASE: data, MYSQL_USER: mysql, MYSQL_PASSWORD: mysql, MYSQL_ALLOW_EMPTY_PASSWORD: 'yes', MYSQL_ROOT_PASSWORD: 'root' }
nginx:
    image: 'nginx:1.9.0'
    volumes: ['./docker/conf/nginx.conf:/etc/nginx/conf.d/default.conf', './:/var/platform', './docker/ssl/nginx.crt:/etc/nginx/ssl/nginx.crt', './docker/ssl/nginx.key:/etc/nginx/ssl/nginx.key']
    ports: ['80', '443']
    links: [phabricator]
    environment:
      VIRTUAL_HOST: phabricator.platform
      PLATFORM_DOCKER: phabricator
